/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'title' : string,
  'description' : string,
  'isNewRelease' : boolean,
  'author' : string,
  'isFeatured' : boolean,
  'category' : BookCategory,
  'rating' : number,
  'price' : number,
}
export type BookCategory = { 'nonFiction' : null } |
  { 'academic' : null } |
  { 'fiction' : null };
export interface CartItem { 'bookId' : bigint, 'quantity' : bigint }
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Order {
  'status' : OrderStatus,
  'orderId' : bigint,
  'totalAmount' : number,
  'placedAt' : bigint,
  'shippingAddress' : string,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'bookId' : bigint,
  'quantity' : bigint,
  'priceAtPurchase' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<[Book], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getBook' : ActorMethod<[bigint], Book>,
  'getBooksByCategory' : ActorMethod<[BookCategory], Array<Book>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFeaturedBooks' : ActorMethod<[], Array<Book>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getNewReleases' : ActorMethod<[], Array<Book>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBooks' : ActorMethod<[string], Array<Book>>,
  'submitContactForm' : ActorMethod<[ContactForm], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];