/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookCategory = IDL.Variant({
  'nonFiction' : IDL.Null,
  'academic' : IDL.Null,
  'fiction' : IDL.Null,
});
export const Book = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isNewRelease' : IDL.Bool,
  'author' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : BookCategory,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'bookId' : IDL.Nat,
  'quantity' : IDL.Int,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func([Book], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBook' : IDL.Func([IDL.Nat], [Book], ['query']),
  'getBooksByCategory' : IDL.Func([BookCategory], [IDL.Vec(Book)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getNewReleases' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookCategory = IDL.Variant({
    'nonFiction' : IDL.Null,
    'academic' : IDL.Null,
    'fiction' : IDL.Null,
  });
  const Book = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isNewRelease' : IDL.Bool,
    'author' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : BookCategory,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({ 'bookId' : IDL.Nat, 'quantity' : IDL.Int });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addBook' : IDL.Func([Book], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBook' : IDL.Func([IDL.Nat], [Book], ['query']),
    'getBooksByCategory' : IDL.Func([BookCategory], [IDL.Vec(Book)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getNewReleases' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };